# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'zxhsc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'ALCameraViewController'
pod 'IQKeyboardManagerSwift' #, '~> 4.0.6'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'Alamofire', '~> 4.5.1'
pod 'SDWebImage'
pod 'SnapKit'
pod 'PYSearch'
pod 'YBPopupMenu'
pod 'WZLBadge'
pod 'SKTagView'
pod 'UITableView+FDTemplateLayoutCell'
pod 'ObjectMapper'
pod 'pop'
pod 'SSKeychain'
pod 'FMDB'
pod 'swiftScan', '~> 1.1.1'
pod 'Charts'

pod 'SwiftyJSON'
pod 'JPush'

pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

pod 'BaiduMapKit' #百度地图SDK

end
