# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'zxhsc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'ALCameraViewController'
pod 'IQKeyboardManagerSwift' #, '~> 4.0.6'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'Alamofire'#, '~> 4.5.1'
pod 'SDWebImage' #, '~> 4.0.0'
pod 'SnapKit'
pod 'PYSearch'
pod 'YBPopupMenu'
pod 'WZLBadge'
pod 'SKTagView'
pod 'UITableView+FDTemplateLayoutCell'
pod 'ObjectMapper'
pod 'pop'
pod 'SSKeychain'
pod 'FMDB'
pod 'swiftScan'#, '~> 1.1.1'
pod 'Charts'
pod 'HUPhotoBrowser' 

pod 'SwiftyJSON'
pod 'JPush'

# 主模块(必须)
pod 'mob_sharesdk'
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'mob_sharesdk/ShareSDKUI'
pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
# 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
pod 'mob_sharesdk/ShareSDKExtension'

pod 'BaiduMapKit' #百度地图SDK

end
